### ISSUE TITLE
Implement Main Menu

### ISSUE THREAD

**Issue by vogles** [dpati007/GameJam2017#4]

**Comment by rslay** [comment]
How do I put the things on the glowing rectangle?????¿¿¿¿

**Comment by vogles** [comment]
@Sumlerd Hey it's ready

**Comment by vogles** [comment]
@rslay asdf

**Comment by rslay** [comment]
Cleaned that up, let me know if the design is done, I don't think its too important, you might have to drag in the scenes since I'm using a different ver on mac, @Sumlerd had that issue

**Comment by vogles** [comment]
- [ ] Maybe swap out textures for something prettier
